name = "cake_pog"
version = "1.1.0"
description = "ğŸ‚Cake ğŸ˜PostgreSQL adapter which passes PreparedStatements to the pog library for execution written in Gleam."
licences = ["MPL-2.0"]
repository = { type = "github", user = "inoas", repo = "gleam-cake-pog" }
# links = [{ title = "Website", href = "https://gleam.run" }]

gleam = ">= 1.6.0"

[documentation]
pages = [
    { title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
]

[dependencies]
cake = ">= 2.0.0 and < 3.0.0"
gleam_stdlib = ">= 0.50.0 and < 2.0.0"
pog = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
birdie = ">= 1.2.5 and < 2.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
pprint = ">= 1.0.4 and < 2.0.0"
